config/routes.rb
Rails3BootstrapDeviseCancan::Application.routes.draw do
  resources :comments

  resources :articles do
    resources :comments
  end

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"

  devise_for :users

  resources :users do
    get 'list', :on => :collection
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
   attr_accessible :title, :body , :user_id, :article_id
   belongs_to :user
   belongs_to :article
   default_scope :order => 'created_at DESC'

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource

  # GET /comments/1/edit
  def edit
    @comment = Comment.find(params[:id])
  end

  # POST /comments
  # POST /comments.json
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(params[:comment])
    @comment.user_id=current_user.id

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @article, notice: 'Comment was successfully created.' }
        format.json { render json: @comment, status: :created, location: @comment }
      else
        format.html { redirect_to @article, notice: 'Somethings went wrong' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /comments/1
  # PUT /comments/1.json
  def update
    @comment = Comment.find(params[:id])

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to @comment.article, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to comments_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comments.html.haml
%h4 Listing comments
-if !@comments.nil?
  - @comments.each do |comment|
    .comment
      = comment.body
      %br
      By #{User.find(comment.user_id).name}
      %br
      -if !current_user.nil?
        -if current_user.id==comment.user_id
          = link_to 'Edit', edit_comment_path(comment)
        -if can? :destroy, @article
          = link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' }
      %br
  =paginate @comments
-else
  %p No comments
%br
-if !current_user.nil?
  = render "comments/form"

app/views/comments/_form.html.haml
= simple_form_for([@article, @comment]) do |f|
  = f.error_notification
  %p Leave your comment:
  = f.text_field :body
  %br
  = f.button :submit

app/views/comments/edit.html.haml
%h1 Editing comment

= render 'form'

= link_to 'Show', @comment
\|
= link_to 'Back', comments_path

app/views/comments/new.html.haml
%h1 New comment

= render 'form'

= link_to 'Back', comments_path