config/routes.rb
Rails3BootstrapDeviseCancan::Application.routes.draw do
  resources :comments

  resources :articles do
    resources :comments
  end

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"

  devise_for :users

  resources :users do
    get 'list', :on => :collection
  end
end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :content, :title, :user_id
  belongs_to :user
  has_many :comments, :dependent => :destroy

  validates :title, :presence => true, :length => { :within => 1..140}
  default_scope :order => 'created_at DESC'
end

app/controllers/articles_controller.rb
#require 'will_paginate/array'
class ArticlesController < ApplicationController
  load_and_authorize_resource

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.page(params[:page]).per(5)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @articles }
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @article = Article.find(params[:id])
    @comment= Comment.new
    @comments=@article.comments.page(params[:page]).per(10)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @article }
    end

  end

  # GET /articles/new
  # GET /articles/new.json
  def new
    @article = Article.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/1/edit
  def edit
    @article = Article.find(params[:id])
  end

  # POST /articles
  # POST /articles.json
  def create
    #@article = Article.new(params[:article])
    @article = current_user.articles.build(params[:article])

    respond_to do |format|
      if @article.save
        format.html { redirect_to articles_path, notice: 'Article was successfully created.' }
        format.json { render json: @article, status: :created, location: @article }
      else
        format.html { render action: "new" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /articles/1
  # PUT /articles/1.json
  def update
    @article = Article.find(params[:id])

    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to articles_path, notice: 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_articles.html.haml
-@articles.each do |article|
  .article
    =link_to article.title, article, :class=> 'article_title'
    =simple_format article.content
    %p Author: #{article.user.name}
  %br

app/views/articles/_form.html.haml
= simple_form_for(@article) do |f|
  = f.error_notification

  .form-inputs
    = f.input :title
    = f.text_area :content, :id=>"some-textarea"

  .form-actions
    = f.button :submit

app/views/articles/edit.html.haml
%h1 Editing article

= render 'form'

= link_to 'Show', @article
\|
= link_to 'Back', articles_path

app/views/articles/index.html.haml
-if can? :create, @article
  = link_to 'New Article', new_article_path
%br
%br
-@articles.each do |article|
  .article
    =link_to article.title, article, :class=> 'article_title'
    =simple_format article.content
    %p Author: #{article.user.name}
    -if can? :update, @article
      = link_to 'Edit', edit_article_path(article)
    -if can? :destroy, @article
      = link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' }
  %br
= paginate @articles

app/views/articles/new.html.haml
%h1 New article

= render 'form'

= link_to 'Back', articles_path

app/views/articles/show.html.haml
.article
  %h4 #{@article.title}
  %br
  %p
    =simple_format @article.content

-if can? :update, @article
  = link_to 'Edit', edit_article_path(@article)
-if can? :destroy, @article
  = link_to 'Destroy', @article, method: :delete, data: { confirm: 'Are you sure?' }
%br
= render "comments/comments"